spring:
  application:
    name: Gateway
  data:
    redis:
      #      host: 192.168.126.128
      #    host: redis
      host: 43.139.99.4
      port: 6379
      password: pmos@123
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8081
          predicates:
            - Path=/user/*
        - id: OrderService
          uri: http://localhost:8082
          predicates:
            - Path=/order/*
server:
  port: 8088
pmos:
  jwt:
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /user/login
      - /user/login**
      - /user/register**
      - /items/**
      - /hi
