spring:
  application:
    name: Gateway
  data:
    redis:
      #      host: 192.168.126.128
      #    host: redis
      host: ${pmos.redis.host}
      port: 6379
      password: ${pmos.redis.pw}
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8081
          predicates:
            - Path=/user/*
        - id: OrderService
          uri: http://localhost:8082
          predicates:
            - Path=/order/*
        - id: PayService
          uri: http://localhost:8083
          predicates:
            - Path=/pay/*
        - id: SocialService
          uri: http://localhost:8084
          predicates:
            - Path=/social/*
server:
  port: 8088
pmos:
  jwt:
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /user/login
      - /user/login**
      - /user/register**
      - /items/**
      - /hi
